-- VHDL generated by gates

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Function: add
entity add is
  port (
    clk   : in  std_logic;
    reset : in  std_logic;
    a : in std_logic_vector(31 downto 0);
    b : in std_logic_vector(31 downto 0);
    result : out std_logic_vector(31 downto 0)
  );
end entity;

architecture behavioral of add is
  signal sum : std_logic_vector(31 downto 0);
begin
  process(clk, reset)
  begin
    if reset = '1' then
      sum <= (others => '0');
    elsif rising_edge(clk) then
      sum <= std_logic_vector(unsigned(a) + unsigned(b));
      result <= sum;
    end if;
  end process;
end architecture;

