-- VHDL generated by gates

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Function: abs_val
entity abs_val is
  port (
    clk   : in  std_logic;
    reset : in  std_logic;
    x : in std_logic_vector(31 downto 0);
    result : out std_logic_vector(31 downto 0)
  );
end entity;

architecture behavioral of abs_val is
begin
  process(clk, reset)
  begin
    if reset = '1' then
    elsif rising_edge(clk) then
      if unsigned(x) < to_unsigned(0, 32) then
        result <= std_logic_vector(to_unsigned(0, 32) - unsigned(x));
      else
        result <= x;
      end if;
    end if;
  end process;
end architecture;

