-- VHDL generated by gates

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

-- Function: loop_sum
entity loop_sum is
  port (
    clk   : in  std_logic;
    reset : in  std_logic;
    n : in std_logic_vector(31 downto 0);
    result : out std_logic_vector(31 downto 0)
  );
end entity;

architecture behavioral of loop_sum is
  signal sum : std_logic_vector(31 downto 0);
  signal i : std_logic_vector(31 downto 0);
begin
  process(clk, reset)
  begin
    if reset = '1' then
      sum <= (others => '0');
      i <= (others => '0');
    elsif rising_edge(clk) then
      sum <= std_logic_vector(to_unsigned(0, 32));
      i <= std_logic_vector(to_unsigned(0, 32));
      while unsigned(i) < unsigned(n) loop
        sum <= std_logic_vector(unsigned(sum) + unsigned(i));
        i <= std_logic_vector(unsigned(i) + to_unsigned(1, 32));
      end loop;
      result <= sum;
    end if;
  end process;
end architecture;

